language: go
matrix:
  include:
    - os: linux
      go: 1.7.x
    - os: linux
      go: 1.8.x
    - os: osx
      go: 1.8.x
script:
  - make ci
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
