language: go
matrix:
  include:
    - os: linux
      go: 1.7.x
    - os: linux
      go: 1.8.x
    - os: osx
      go: 1.8.x
script:
  - go test -v $(go list ./...)
  - go test -integration -v $(go list ./...)
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
